### ISSUE TITLE
Definition for rule '...' was not found.

### ISSUE THREAD

**Issue by janwerkhoven** [grrakesh4769/atom-ember-template-lint#86]
**Describe the bug**

When linting rules are turned off in `.template-lintrc.js` warnings are shown that the definitions of these rules are not known.

**To Reproduce**

Update `.template-lintrc.js` to:

```js
'use strict';

module.exports = {
  extends: 'octane',

  rules: {
    'no-down-event-binding': 'off',
    'no-duplicate-id': 'off',
    'no-duplicate-landmark-elements': 'off',
    'no-redundant-landmark-role': 'off',
    'require-input-label': 'off'
  }
};
```

Close and reopen Atom.
Open any `.hbs` file in the Ember repo.
Error message appear: "Definition for rule 'no-down-event-binding' was not found."
See screenshot below.
If you then remove the `rules: { ... }` from `.template-lintrc.js`, reopen Atom, these errors are gone too.

**Expected behavior**

No "definition not found" errors should appear.

**Screenshots**

<img width="632" alt="Screen Shot 2021-05-29 at 10 41 42" src="https://user-images.githubusercontent.com/4415419/120052833-9c859a80-c06a-11eb-9a9b-5727285d80f6.png">

**Desktop (please complete the following information):**

- OS: macOS Big Sur v11.3
- Atom: v1.57.0
   - atom-ember-template-lint: v4.1.0
   - linter: v3.3.1

package.json
```json
  ...
  "devDependencies": {
    "@ember/optional-features": "^2.0.0",
    "@ember/test-helpers": "^2.2.5",
    "@glimmer/component": "^1.0.4",
    "@glimmer/tracking": "^1.0.4",
    "babel-eslint": "^10.1.0",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^1.11.3",
    "ember-cli": "~3.26.1",
    "ember-cli-app-version": "^5.0.0",
    "ember-cli-babel": "^7.26.3",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-htmlbars": "^5.7.1",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.1",
    "ember-data": "~3.27.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.0.4",
    "ember-load-initializers": "^2.1.2",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-page-title": "^6.2.1",
    "ember-qunit": "^5.1.4",
    "ember-resolver": "^8.0.2",
    "ember-source": "~3.26.1",
    "ember-template-lint": "^3.2.0",
    "eslint": "^7.23.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-ember": "^10.3.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "loader.js": "^4.7.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.2.1",
    "qunit": "^2.14.1",
    "qunit-dom": "^1.6.0"
  },
  ...
```

**Additional context**

Loving your work, keep it up! ❤️

**Comment by janwerkhoven** [comment]
@grrakesh4769 This PR https://github.com/grrakesh4769/atom-ember-template-lint/pull/92 will solve this issue. Please merge and release. :)

**Comment by grrakesh4769** [comment]
PR #92 has been merged. Sorry for not getting to this sooner.
